include /etc/nginx/cors-map.conf;

server {
  listen 80;
  server_name svoi.hakolr.dev;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location /api/ {
    client_max_body_size 8m;
    include /etc/nginx/proxy.conf;
    include /etc/nginx/api-cors.conf;
    proxy_pass http://backend:3001;
  }

  location / {
    include /etc/nginx/proxy.conf;
    proxy_pass http://frontend:3000;
  }
}

server {
  listen 80;
  server_name admin.svoi.hakolr.dev;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    include /etc/nginx/proxy.conf;
    proxy_pass http://admin:80;
  }
}
