server {
  listen 80;
  server_name svoi.hakolr.dev www.svoi.hakolr.dev admin.svoi.hakolr.dev;

  location /.well-known/acme-challenge/ {
    root /var/www/certbot;
  }

  location / {
    return 301 https://$host$request_uri;
  }
}

server {
  listen 443 ssl;
  server_name www.svoi.hakolr.dev;

  ssl_certificate /etc/letsencrypt/live/svoi.hakolr.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/svoi.hakolr.dev/privkey.pem;

  return 301 https://svoi.hakolr.dev$request_uri;
}

server {
  listen 443 ssl;
  server_name svoi.hakolr.dev;

  ssl_certificate /etc/letsencrypt/live/svoi.hakolr.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/svoi.hakolr.dev/privkey.pem;

  location /api/ {
    include /etc/nginx/proxy.conf;
    proxy_pass http://backend:3001;
  }

  location / {
    include /etc/nginx/proxy.conf;
    proxy_pass http://frontend:3000;
  }
}

server {
  listen 443 ssl;
  server_name admin.svoi.hakolr.dev;

  ssl_certificate /etc/letsencrypt/live/svoi.hakolr.dev/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/svoi.hakolr.dev/privkey.pem;

  location / {
    include /etc/nginx/proxy.conf;
    proxy_pass http://admin:80;
  }
}
